name: Bug Report
description: File a bug report.
title: "🐛 "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Bug description
      description: Describe the bug
      placeholder: Ran {this}, did {that}, expected {the other}
    validations: 
      required: true
  - type: input
    attributes:
      label: Adapter
      description: The AdapterKind if known  
  - type: input
    attributes:
      label: Model
      description: The Model name if known
  - type: textarea
    attributes:
      label: Suggested Resolution